layouts_dir: "_layouts"
host: "0.0.0.0"
#baseurl: "/StringTrax"
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      title: String Trax
      image: /img/Social.png
      description: Professional violin and vocal tracks
      keywords: Kallen O'Connor, recording, violin, vocal